force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>HUF</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PostToChatterService.cls
public with sharing class PostToChatterService {
  public static void postToChatterGroup(Id groupId, List<Trade__c> trades) {
    List<FeedItem> feedItems = new List<FeedItem>();
    for (Trade__c trade : trades) {
      feedItems.add(
        new FeedItem(
          ParentId = groupId,
          Title = trade.Name + 'trade created',
          Status = 'Published',
          Body = getBodyFromTemplate(trade)
        )
      );
    }
    insert feedItems;
  }

  private static String getBodyFromTemplate(Trade__c trade) {
    return 'A new trade has been created with the following data:' +
      '\nSell Currency: ' +
      trade.Sell_Currency__c +
      '\nSell Amount: ' +
      trade.Sell_Amount__c +
      '\nBuy Currency: ' +
      trade.Buy_Currency__c +
      '\nBuy Amount: ' +
      trade.Buy_Amount__c +
      '\nRate: ' +
      trade.Rate__c +
      '\nBooked Date: ' +
      trade.CreatedDate +
      '\nLink: ' +
      URL.getSalesforceBaseUrl().toExternalForm() +
      '/' +
      trade.Id;
  }
}