force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <label>Sell Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>GBP</fullName>
    </customValue>
    <customValue>
        <fullName>KRW</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>HUF</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <masterLabel>Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TradesController.cls
public with sharing class TradesController {
  @AuraEnabled(cacheable=true)
  public static List<Trade__c> getAllTrade() {
    return [
      SELECT
        Id,
        Name,
        Buy_Amount__c,
        Buy_Currency__c,
        Sell_Amount__c,
        Sell_Currency__c,
        Rate__c,
        CreatedDate
      FROM Trade__c
      WITH SECURITY_ENFORCED
      ORDER BY CreatedDate DESC
      LIMIT 100
    ];
  }

  /**
   * @description
   * Do a Callout to Flexi api to Fetch the actual currency rate
   * @param baseCurrency
   * @param targetCurrency
   * @return
   * @example
   */
  @AuraEnabled
  public static RateCalloutWrapper.Rate getRate(
    String baseCurrency,
    String targetCurrency
  ) {
    RateCalloutService calloutService = new RateCalloutService(
      baseCurrency,
      targetCurrency
    );
    RateCalloutWrapper.Rate fetchedRate = calloutService.doCallout();
    return fetchedRate;
  }
}